### ISSUE TITLE
Check if Stella / Rob have permissions to import issues from their fork into OpenSourceBrain

### ISSUE THREAD

**Issue by robertvi** [OpenSourceBrain/SBMLShowcase#17]
If it's possible, it would probably make more sense to import the existing issues rather than recreate then and their threads. We can drop permissions down again afterwards if required.

**Comment by pgleeson** [comment]
I've bumped up your permissions now...

**Comment by robertvi** [comment]
I now see that it's only possible between repos in the same organisation/account, so apparently between forks will not work :(

**Comment by robertvi** [comment]
Having asked my ARC colleagues if only way seems to be to use github command line and checkout both repos locally, and do the moving process there. If so I don't think it's worth learning all the new commands etc, so we will just leave the existing issues on our fork and start one issues on the main repository here.
