### ISSUE TITLE
Create summary table of whether omex file runs locally in different simulators 

### ISSUE THREAD

**Issue by stellaprins** [OpenSourceBrain/SBMLShowcase#23]
Create overview table like the one below for locally ran models (different than the one tested below).

- [ ] run directly with tellurium (maybe other options down the line)
- [ ] run with biosimulators docker locally (on all the different engines)
- [ ] run with biosimulators remotely (on all the different engines) pynml API does this currently (check [this](https://github.com/NeuroML/pyNeuroML/blob/development/pyneuroml/biosimulations.py#L167))

Use helper functions that Rob wrote.

Down the line:
- [ ] incorperate process (for creating the table) in github actions and automate it as a test.

The resulting minimal omex file SBML\LEMS_NML2_Ex9_FN.omex [biosimulations tool](https://run.biosimulations.org/runs/new) was used to run simulations on https://run.biosimulations.org/

Simulator: [tellurium 2.2.8](https://biosimulators.org/simulators/tellurium) (Sensible output was produced)
Simulator: [copasi 4.42.284](https://biosimulators.org/simulators/copasi) Failed
Simulator: [amici 0.18.1](https://biosimulators.org/simulators/amici) (No output was produced)
Simulator: [vcell 7.5.0.127](https://biosimulators.org/simulators/vcell) (No output was produced)
Simulator: [pysces 1.2.1](https://biosimulators.org/simulators/pysces) Failed
Simulator: [gillespy2 1.6.6](https://biosimulators.org/simulators/gillespy2) (No sensible output was produced, flat line)
Simulator: [libsbmlsim 1.4.0](https://biosimulators.org/simulators/libsbmlsim) (Sensible output was produced)
Simulator: [masspy 0.1.6](https://biosimulators.org/simulators/masspy) Failed

**Comment by sanjayankur31** [comment]
https://github.com/NeuroML/pyNeuroML/blob/development/pyneuroml/biosimulations.py#L167 -> function to simulate an omex archive on biosimulators using its API

**Comment by stellaprins** [comment]
Github actions is failing, Rob and myself have been looking at it but have not found a solution yet. Any clues what is going on @sanjayankur31 or @pgleeson? We think it may be more related to a conflict in package version than changes to the code.

` ImportError: cannot import name 'VisibleDeprecationWarning' from 'numpy' (/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/numpy/__init__.py)` (see for example [here](https://github.com/OpenSourceBrain/SBMLShowcase/actions/runs/9546342662/job/26309000594))


`ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject` (see for example [here](https://github.com/OpenSourceBrain/SBMLShowcase/actions/runs/9546342662/job/26309000818))

**Comment by sanjayankur31** [comment]
Hello,

Yes, looks like the version of Brian that's being pulled in is 2.5.3, which doesn't seem to have the necessary fixes for numpy2.x support, which were made in 2.6.0:

https://github.com/brian-team/brian2/commit/e8f05c6461d7c530ca26bdbab474a1891d9036b0

OMV uses 2.5.3 as the default version from the looks of it:

https://github.com/OpenSourceBrain/osb-model-validation/blob/e2b060dbcb3d82a1236cd14896b5c1db6a8476ab/omv/engines/getbrian2.py#L6

Numpy2.x was only released yesterday, so we'll have to update omv to work with that.

I think a current workaround is to explicitly install `numpy<=1.2.3`, as has been done here:

**Comment by sanjayankur31** [comment]
The other error is probably also because pytables is not ready for numpy 2.x, so pinning numpy should fix that too.

```
Requirement already satisfied: numpy in /opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages (from libNeuroML>=0.5.5->pyneuroml) (2.0.0)
```

**Comment by stellaprins** [comment]
Your first suggestion appears to have solved the github actions problems! Thanks a lot @sanjayankur31.

**Comment by sanjayankur31** [comment]
FYI: json files including format information:

- information about simulators: [biosimulators.json](https://github.com/user-attachments/files/15987472/biosimulators.json); the "modelFormat" field for each simulator links to an EDAM id in the ontologies file:
- the ontologies file where the formats etc have uniq EDAM ids: [ontologies.json](https://github.com/user-attachments/files/15987471/ontologies.json)
