### ISSUE TITLE
Add missing xlmns:sbml attribute colum to test suite output table 

### ISSUE THREAD

**Issue by stellaprins** [OpenSourceBrain/SBMLShowcase#26]
To do:
- [x] make sure <process_test_suite.py> runs and gives the correct output
- [x] add fix for SED-ML files with missing `xlmns:sbml` attributes
- [x] add column that records whether `xlmns:sbml` attribute is missing
- [x] check whether columns displays well in github

If there are errors generated, categorise errors to identify whether they come from the docker. Rob's categorisation won't work as he has written it for local runs of tellurium (see [here](https://github.com/OpenSourceBrain/SBMLShowcase/blob/6c550b9a2462095c4cfaef0958d4f5c26c780d08/utils/__init__.py#L25)).

**Comment by stellaprins** [comment]
<process_test_suite.py> runs and createds an output table that looks correct to me (see screenshot below, I only tested 5 files). 

![image](https://github.com/OpenSourceBrain/SBMLShowcase/assets/30465823/ac1beca1-2adf-4a21-bc62-1ae239742a80)

However, I am still dealing with the initial issue of the matplotlib windows that pop up and have to be closed manually so will look into that first.

**Comment by sanjayankur31** [comment]
> However, I am still dealing with the initial issue of the matplotlib windows that pop up and have to be closed manually so will look into that first.



The way we do it in pyNeuroML is to not call `plt.show()` at all if we don't want to matplotlib plots to pop up---they can still be saved to files without it.

https://github.com/NeuroML/pyNeuroML/blob/development/pyneuroml/plot/Plot.py#L415

If that's not possible (something else is calling matplotlib), one can set the "matplotlib backend" to a "non-interactive" one right at the beginning of the script too (hopefully the code calling matplotlib doesn't then set a backend itself though):

https://matplotlib.org/stable/users/explain/figure/backends.html#selecting-a-backend

```
import matplotlib
matplotlib.use("agg")

... 
```

has generally worked for me

**Comment by stellaprins** [comment]
Thanks @sanjayankur31, fixed it using `matplotlib.use("agg")`.

I'm trying to make a branch from the OpenSourceBrain/SBMLShowcase/test_omex branch for thiss specific issue but get the error below. 

![image](https://github.com/OpenSourceBrain/SBMLShowcase/assets/30465823/98c5365d-6ab4-4fa8-805a-8ff6d2b7c060)

**Comment by sanjayankur31** [comment]
Hrm, not sure about the vscode issue (i dont use it myself). I see no
reason why it shouldnt work. I guess you could create it on github and then
pull to use it as a workaround?
-- 
Thanks,

Ankur

(Sent from mobile device)

**Comment by stellaprins** [comment]
It is not an issue with VS code, I've also tried to do it using SourceTree and via GitHub directly, and with git commands, but got the same errors. 

I believe I've found the issue. I think the problem was that `/` are not accepted in the branch name.

**Comment by sanjayankur31** [comment]
> It is not an issue with VS code, I've also tried to do it using SourceTree and via GitHub directly, and with git commands, but got the same errors.
> 
> I believe I've found the issue. I think the problem was that `/` are not accepted in the branch name.

No, `/`s are fine in branch names, I use `feat/...` for all my branches pretty much---it's a commonly used git convention :thinking: 

Some digging got me to this:

https://stackoverflow.com/questions/45141188/git-fatal-cannot-lock-ref

So, because there's already a *local* branch `test_omex`, one cannot create new branches prefixed with `test_omex/`. If I create a new clone of the repo, not checkout `test_omex` locally, I can create a branch `test_omex/...` just fine:


```
git checkout -b test_omex/ankur-test origin/test_omex
```

We'll have to use `test_omex_feature-whatever` to workaround this if it's already been checked out for a local branch. I can't check out `test_omex` here now :D

**Comment by stellaprins** [comment]
Thanks! Yes, I normally use `/` in branch names for my other project too. The convention for naming branches I would normally use for branches from a source branch called `dev/feature` would be `feature/issue_number-issue_title`. 

I've deleted my local repository, and tried to create a branch with test_omex as source branch, called `test_omex/26-add_atributes` but I am getting the same error here (without the test_omex branch existing locally). However, you're right, when I then locally create a branch `test_omex/26-add_atributes` with the remote `origin/test_omex` as source branch (without checking it out locally), I am able to create the `test_omex/26-add_atributes` branch. Will move forward using `test_omex__issue_number-issue_title`.
