### ISSUE TITLE
Failing GitHub Actions workflows or failing local runs

### ISSUE THREAD

**Issue by stellaprins** [OpenSourceBrain/SBMLShowcase#58]
Quite often GitHub Actions is temporarily failing or there are problems running scripts locally (e.g. docker stops working). To get a better idea of how often this happens and in which situations.

**Comment by stellaprins** [comment]
<img src="https://github.com/user-attachments/assets/5fe5e228-51de-48f6-8de4-b16633f0ebb3" width="300"/>

**Comment by sanjayankur31** [comment]
This seems to be some sort of issue with Docker on Windows, unfortunately. Lots of folks have filed issues about it :crying_cat_face: 

https://github.com/docker/for-win/issues?q=is%3Aissue%20state%3Aopen%20WSL%20terminated%20abruptly
