### ISSUE TITLE
Check biosimulators compatibility tables

### ISSUE THREAD

**Issue by stellaprins** [OpenSourceBrain/SBMLShowcase#61]
- Copasi should have been updated now and should show up as a `pass` when running valid omex files created using SBML and SED-ML files. Check whether this is the case.
- double check Brian2 compatible formats (@pgleeson noticed that too many formats may have been listed as compatible)

**Comment by stellaprins** [comment]
engine information was taken from the biosimulators docs ([here](https://docs.biosimulations.org/users/biosimulators-packages/)). The [Brian2 page ](https://docs.biosimulators.org/Biosimulators_pyNeuroML/) lists the following compatibility:

>  [COMBINE/OMEX archives](https://combinearchive.org/) that describe one or more simulation experiments (in [SED-ML format](https://sed-ml.org/)) of one or more models (in [NeuroML](https://neuroml.org/) / [LEMS](https://lems.github.io/LEMS/) format).

**Comment by stellaprins** [comment]
I realised I put a placeholder for the Smoldyn compatible formats because I could not find them. From the documentation [here](https://github.com/ssandrews/Smoldyn?tab=readme-ov-file), I gather that any model model format is Smoldyn compatible when it is packaged as an omex file with a valid SED-ML file? @pgleeson @sanjayankur31, do you know whether this is correct?

**Comment by pgleeson** [comment]
@stellaprins I get the impression that the only real format Smoldyn supports is its own, so an omex file with a sed-ml pointing to a smoldyn model is fine for it, but anything else it will fail. I think Smoldyn can export to sbml, but that's not relevant in this scenario.

**Comment by stellaprins** [comment]
Thanks @pgleeson! Will update the engines dict.
